export const DETAIL_MOVIE_START = "DETAIL_MOVIE_START";
export const DETAIL_MOVIE_FAILED = "DETAIL_MOVIE_FAILED";
export const DETAIL_MOVIE_SUCCESS = "DETAIL_MOVIE_SUCCESS";

export const GET_CREDITS_START = "GET_CREDITS_START";
export const GET_CREDITS_FAILED = "GET_CREDITS_FAILED";
export const GET_CREDITS_SUCCESS = "GET_CREDITS_SUCCESS";
