export const GET_LIST_START = "GET_LIST_START";
export const GET_LIST_FAILED = "GET_LIST_FAILED";
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS";

export const LOAD_MORE_START = "LOAD_MORE_START";
export const LOAD_MORE_FAILED = "LOAD_MORE_FAILED";
export const LOAD_MORE_SUCCESS = "LOAD_MORE_SUCCESS";
