export const SEARCH_MOVIES_START = "SEARCH_MOVIES_START";
export const SEARCH_MOVIES_FAILED = "SEARCH_MOVIES_FAILED";
export const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS";

export const MORE_RESULTS_START = "MORE_RESULTS_START";
export const MORE_RESULTS_FAILED = "MORE_RESULTS_FAILED";
export const MORE_RESULTS_SUCCESS = "MORE_RESULTS_SUCCESS";
